# Automatically updated by the winget bot at 2021/Sep/14
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: ActiveState.ActivePerl
PackageVersion: 5.28.1001
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://cli-msi.s3.amazonaws.com/ActivePerl-5.28.msi
  InstallerSha256: C2EFDF28476AF93E82BC58B6987A7D12B9105B135991689A586ECBB5A0D9D527
  UpgradeBehavior: install
  ProductCode: '{FAFB92A9-5A72-07A0-81D6-751F7EF75E63}'
ManifestType: installer
ManifestVersion: 1.0.0
