# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Google.Chrome
PackageVersion: 93.0.4577.82
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise64.msi
  InstallerSha256: 7B8928C94318E843C4C421E0C5752FF3AE77897E0E0D28DD061BEDC8E3602BD3
  UpgradeBehavior: install
  ProductCode: "{FBD2AE44-E2BC-3069-88AA-05B04DD7B6CE}"
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi
  InstallerSha256: 60EC70E7BF0F6859338554EB42B1465921CE0BCE723449AA6BC67079DE27A6E5
  UpgradeBehavior: install
  ProductCode: "{6CAE450F-543D-3385-8585-EBF16BAA1C80}"
ManifestType: installer
ManifestVersion: 1.0.0

